### ISSUE TITLE
While trying to run "yarn add newrelic" - Attempting install in native-metrics module

### ISSUE THREAD

**Issue by gopalakrishnanr-paypaycorp** [newrelic/node-native-metrics#123]
Node Version : v12.18.3
Os : Windows 10

```
[-/10] ⢀ waiting...                                                                                                     
[4/10] ⢀ @newrelic/native-metrics                                                                                       
warning Error running install script for optional dependency: "D:\\p2pWorkspace\\bump-update\\developer-panel-web\\bff\\node_modules\\@newrelic\\native-metrics: Command failed.
Exit code: 1
Command: node ./lib/pre-build.js install native_metrics
Arguments:
Directory: D:\\p2pWorkspace\\bump-update\\developer-panel-web\\bff\\node_modules\\@newrelic\\native-metrics
Output:
============================================================================
Attempting install in native-metrics module. Please note that this is an
OPTIONAL dependency, and any resultant errors in this process will not
affect the general performance of the New Relic agent, but event loop and
garbage collection metrics will not be collected.
============================================================================

> C:\\Program Files\\nodejs\\node.exe D:\\p2pWorkspace\\bump-update\\developer-panel-web\\bff\\node_modules\\node-gyp\\bin\\node-gyp.js clean configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.18.3 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\\Python38\\python.EXE -c import sys; print \"%s.%s.%s\" % sys.version_info[:3];gyp ERR! stack   File \"<string>\", line 1
gyp ERR! stack     import sys; print \"%s.%s.%s\" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:303:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"D:\\\\p2pWorkspace\\\\bump-update\\\\developer-panel-web\\\\bff\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"clean\" \"configure\"
gyp ERR! cwd D:\\p2pWorkspace\\bump-update\\developer-panel-web\\bff\\node_modules\\@newrelic\\native-metrics
gyp ERR! node -v v12.18.3
```

**Comment by carlo-808** [comment]
@gopalakrishnanr-paypaycorp It looks like you are using `node-gyp` version `3.8.0` and I believe that requires python v2.7.  It looks like you are using python v 3.8 here.  Is that correct?  The build should work if you upgrade `npm` which will in turn upgrade `node-gyp`.  What version of `npm` are you running?

**Comment by gopalakrishnanr-paypaycorp** [comment]
@carlo-808 
Python Version - 3.8.5
Npm Version - 6.14.6

**Comment by carlo-808** [comment]
For some reason, it seems that you are using node-gyp 3.8.0 and that is not the one packages with the npm version you are running.  What version of node-gyp do you see when you run this command `npm ls -g node-gyp` ?

**Comment by gopalakrishnanr-paypaycorp** [comment]
@carlo-808 Thanks for answer. Thats works for me..

`yarn --python-mirror=https://npm.taobao.org/mirrors/python/2.7.15/python-2.7.15.msi global add windows-build-tools `
