### ISSUE TITLE
Fails to Install on MacOS even When Developer Command Line Tools Are Installed

### ISSUE THREAD

**Issue by terrybondy** [newrelic/node-native-metrics#71]
```
mrk-tbondy-m:191211_GIR-28438-unhandled-reject2 tbondy$ yarn install
yarn install v1.19.2
info No lockfile found.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning xregexp > @babel/runtime-corejs2 > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning rewire > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
[1/9] ⠠ gc-stats
[2/9] ⠠ ref
[3/9] ⠠ @newrelic/native-metrics
[4/9] ⠠ node-memwatch
.
.
.
warning Error running install script for optional dependency: "/Users/tbondy/Documents/git/pe/gir-conversation-provider-service/191211_GIR-28438-unhandled-reject2/node_modules/@newrelic/native-metrics: Command failed.
Exit code: 1
Command: node ./lib/pre-build.js install native_metrics
Arguments: 
Directory: /Users/tbondy/Documents/git/pe/gir-conversation-provider-service/191211_GIR-28438-unhandled-reject2/node_modules/@newrelic/native-metrics
Output:
============================================================================
Attempting install in native-metrics module. Please note that this is an
OPTIONAL dependency, and any resultant errors in this process will not
affect the general performance of the New Relic agent, but event loop and
garbage collection metrics will not be collected.
============================================================================

> /usr/local/Cellar/node@10/10.17.0/bin/node /usr/local/Cellar/node@10/10.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean configure
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.17.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at \"/usr/bin/python\"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/Cellar/node@10/10.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tbondy/Documents/git/pe/gir-conversation-provider-service/191211_GIR-28438-unhandled-reject2/node_modules/@newrelic/native-metrics/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node@10/10.17.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tbondy/Library/Caches/node-gyp/10.17.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/tbondy/Library/Caches/node-gyp/10.17.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node@10/10.17.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/tbondy/Library/Caches/node-gyp/10.17.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/tbondy/Documents/git/pe/gir-conversation-provider-service/191211_GIR-28438-unhandled-reject2/node_modules/@newrelic/native-metrics',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
> /usr/local/Cellar/node@10/10.17.0/bin/node /usr/local/Cellar/node@10/10.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build -j 6 native_metrics
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.17.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'native_metrics',
gyp info spawn args   'BUILDTYPE=Release',
gyp info spawn args   '-C',
gyp info spawn args   'build',
gyp info spawn args   '--jobs',
gyp info spawn args   6 ]
xcrun: error: active developer path (\"/Applications/Xcode.app/Contents/Developer\") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node@10/10.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:193:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command \"/usr/local/Cellar/node@10/10.17.0/bin/node\" \"/usr/local/Cellar/node@10/10.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"-j\" \"6\" \"native_metrics\"
gyp ERR! cwd /Users/tbondy/Documents/git/pe/gir-conversation-provider-service/191211_GIR-28438-unhandled-reject2/node_modules/@newrelic/native-metrics
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
Failed to execute native-metrics install: No pre-built artifacts for your OS/architecture."
info This module is OPTIONAL, you can safely ignore this error
mrk-tbondy-m:191211_GIR-28438-unhandled-reject2 tbondy$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
mrk-tbondy-m:191211_GIR-28438-unhandled-reject2 tbondy$ ls /Applications/Xcode.app/Contents/Developer
ls: /Applications/Xcode.app/Contents/Developer: No such file or directory
mrk-tbondy-m:191211_GIR-28438-unhandled-reject2 tbondy$ ls /Library/Developer/CommandLineTools
Library		Packages	SDKs		usr
mrk-tbondy-m:191211_GIR-28438-unhandled-reject2 tbondy$ 
```

**Comment by nijotz** [comment]
```
xcrun: error: active developer path (\"/Applications/Xcode.app/Contents/Developer\") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.
```

It seems like there could be a problem with your Xcode setup?

**Comment by terrybondy** [comment]
No, as you can see in the lines following what you quoted, the command line tools are installed, as per instructions in the error message.

**Comment by terrybondy** [comment]
Using `xcode-select --install` does not install anything to `/Applications/Xcode.app/Contents/Developer` so maybe testing for the existence of that directory is too strict.

**Comment by nijotz** [comment]
Would you mind trying: `sudo xcode-select --reset`

**Comment by terrybondy** [comment]
I think this is an issue with node-gyp and my current Xcode installation. I removed the dependency and got the same issue with another nonNR dependency. Closing...

BTW, FWIW
```
mrk-tbondy-m:191211_GIR-28438-unhandled-reject2 tbondy$ sudo xcode-select --reset
Password:
mrk-tbondy-m:191211_GIR-28438-unhandled-reject2 tbondy$ ls /Applications/Xcode.app/Contents/Developer
ls: /Applications/Xcode.app/Contents/Developer: No such file or directory
mrk-tbondy-m:191211_GIR-28438-unhandled-reject2 tbondy$ /Library/Developer/CommandLineTools
-bash: /Library/Developer/CommandLineTools: is a directory
mrk-tbondy-m:191211_GIR-28438-unhandled-reject2 tbondy$ ls /Library/Developer/CommandLineTools
Library		Packages	SDKs		usr
mrk-tbondy-m:191211_GIR-28438-unhandled-reject2 tbondy$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by nijotz** [comment]
Okay, this may help if you haven't seen it yet:
https://stackoverflow.com/questions/35009531/xcrun-error-active-developer-path-applications-xcode-app-contents-developer

**Comment by terrybondy** [comment]
Thanks!
Your suggestion solved my issue!
